import { Cluster, CarpoolingPost, PlacePOI, RegistryStage, FaqItem } from '../types';

export const mockClusters: Cluster[] = [
  {
    id: 'c1-rossi',
    family_name: 'Famiglia Rossi',
    invite_code: 'ROSSI26',
    notes: 'Tavolo amici di università',
    guests: [
      {
        id: 'g1',
        cluster_id: 'c1-rossi',
        first_name: 'Marco',
        last_name: 'Rossi',
        is_attending: null,
        is_child: false,
        dietary_tags: [],
        dietary_notes: '',
        song_request: 'Gigi D\'Agostino - L\'Amour Toujours',
        bus_seat_reserved: true,
      },
      {
        id: 'g2',
        cluster_id: 'c1-rossi',
        first_name: 'Laura',
        last_name: 'Bianchi',
        is_attending: null,
        is_child: false,
        dietary_tags: ['vegetarian'],
        dietary_notes: '',
        song_request: 'Dua Lipa - Levitating',
        bus_seat_reserved: true,
      },
      {
        id: 'g3',
        cluster_id: 'c1-rossi',
        first_name: 'Tommaso',
        last_name: 'Rossi',
        is_attending: null,
        is_child: true,
        dietary_tags: [],
        dietary_notes: 'Menu baby con cotoletta e patatine',
        song_request: '',
        bus_seat_reserved: false,
      }
    ]
  },
  {
    id: 'c2-ferrari',
    family_name: 'Elena & Luca',
    invite_code: 'FERRARI26',
    notes: 'Testimoni di nozze',
    guests: [
      {
        id: 'g4',
        cluster_id: 'c2-ferrari',
        first_name: 'Elena',
        last_name: 'Ferrari',
        is_attending: true,
        is_child: false,
        dietary_tags: ['gluten_free'],
        dietary_notes: 'Celiachia diagnosticata',
        song_request: 'Abba - Dancing Queen',
        bus_seat_reserved: false,
      },
      {
        id: 'g5',
        cluster_id: 'c2-ferrari',
        first_name: 'Luca',
        last_name: 'Moretti',
        is_attending: true,
        is_child: false,
        dietary_tags: [],
        dietary_notes: '',
        song_request: 'The Killers - Mr. Brightside',
        bus_seat_reserved: false,
      }
    ]
  }
];

export const mockCarpooling: CarpoolingPost[] = [
  {
    id: 'cp-1',
    driver_name: 'Matteo Colombo',
    phone_number: '+393401122334',
    departure_location: 'Milano (Stazione Centrale / Rho)',
    departure_time: 'Sabato ore 10:30',
    total_seats: 4,
    available_seats: 2,
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'cp-2',
    driver_name: 'Giulia Rinaldi',
    phone_number: '+393478899001',
    departure_location: 'Bologna Arcoveggio',
    departure_time: 'Sabato ore 12:00',
    total_seats: 3,
    available_seats: 1,
    created_at: '2026-08-20T14:30:00Z',
  }
];

export const mockPlaces: PlacePOI[] = [
  {
    id: 'poi-ceremony-reception',
    name: 'Cascina Ranverso',
    category: 'ceremony',
    latitude: 45.0707046,
    longitude: 7.4514925,
    address: 'Strada degli Abay 36, 10090 Buttigliera Alta (TO)',
    sposi_note: 'Una cascina storica e oasi biologica alle porte della Val di Susa. Qui vivremo sia la cerimonia che il ricevimento, immersi nel verde!',
    is_primary: true,
  },
  {
    id: 'poi-hotel-1',
    name: 'NH Collection Torino Piazza Carlina',
    category: 'hotel',
    latitude: 45.0657215,
    longitude: 7.6893731,
    address: 'Piazza Carlo Emanuele II 15, 10123 Torino (TO)',
    phone: '+39 011 860 1611',
    website_url: 'https://www.nh-collection.com',
    sposi_note: 'Un bellissimo hotel nel cuore di Torino, situato in una delle piazze più eleganti della città.',
  },
  {
    id: 'poi-hotel-2',
    name: 'Turin Palace Hotel',
    category: 'hotel',
    latitude: 45.059512,
    longitude: 7.675034,
    address: 'Via Paolo Sacchi 8, 10128 Torino (TO)',
    website_url: 'https://www.turinpalacehotel.com',
    sposi_note: 'Elegante e a due passi dalla stazione di Porta Nuova. Comodissimo per chi arriva in treno e vuole esplorare il centro a piedi.',
  },
  {
    id: 'poi-hotel-3',
    name: 'Grand Hotel Sitea',
    category: 'hotel',
    latitude: 45.0653,
    longitude: 7.68425,
    address: 'Via Carlo Alberto 35, 10123 Torino (TO)',
    website_url: 'https://grandhotelsitea.it/',
    sposi_note: 'Storico hotel di lusso in pieno centro, a due passi da Piazza San Carlo e via Roma.',
  },
  {
    id: 'poi-hotel-4',
    name: 'Principi di Piemonte | UNA Esperienze',
    category: 'hotel',
    latitude: 45.0650,
    longitude: 7.6817,
    address: 'Via Piero Gobetti 15, 10123 Torino (TO)',
    website_url: 'https://www.unaesperienze.it/',
    sposi_note: 'Uno degli hotel più prestigiosi di Torino, icona dello stile anni 30, con una splendida spa e vista panoramica.',
  },
  {
    id: 'poi-hotel-5',
    name: 'Hotel Victoria Torino',
    category: 'hotel',
    latitude: 45.0651,
    longitude: 7.6845,
    address: 'Via Nino Costa 4, 10123 Torino (TO)',
    website_url: 'https://www.hotelvictoria-torino.com/',
    sposi_note: 'Un hotel dal fascino inconfondibile con un bellissimo giardino interno e una spa favolosa.',
  },
  {
    id: 'poi-hotel-6',
    name: 'Starhotels Majestic',
    category: 'hotel',
    latitude: 45.0625,
    longitude: 7.6811,
    address: 'Corso Vittorio Emanuele II 54, 10123 Torino (TO)',
    website_url: 'https://www.starhotels.com/',
    sposi_note: 'Comodissimo per la vicinanza a Porta Nuova, situato in un magnifico palazzo dell\'Ottocento.',
  },
  {
    id: 'poi-beauty-1',
    name: 'Glamrock Hair Salon',
    category: 'beauty',
    latitude: 45.0605,
    longitude: 7.6475,
    address: 'Corso Racconigi 118/b, 10141 Torino (TO)',
    sposi_note: 'Un salone dall\'atmosfera unica e uno staff super preparato. Consigliatissimo per una piega perfetta, ricordatevi di prenotare per tempo!',
  },
  // Pasticcerie & Bakery
  {
    id: 'poi-food-maicol',
    name: 'Maicol - Croissant Pane Pasticceria',
    category: 'food',
    food_type: 'colazione',
    latitude: 45.0719,
    longitude: 7.6800,
    address: 'Via S. Tommaso 27 c, 10121 Torino (TO)',
    sposi_note: 'Pasticceria artigianale contemporanea straordinaria per colazioni, lievitati d\'autore e i loro celebri croissant quadrati.',
  },
  {
    id: 'poi-food-tari',
    name: 'Tarì - Cake Lab Viennoiserie',
    category: 'food',
    food_type: 'colazione',
    latitude: 45.0617,
    longitude: 7.6865,
    address: 'Via Giuseppe Mazzini 29a, 10123 Torino (TO)',
    sposi_note: 'Laboratorio artigianale di viennoiserie d\'autore e alta pasticceria: croissant sfogliati alla perfezione e pain au chocolat fragranti per una colazione da sogno.',
  },
  {
    id: 'poi-food-tauer',
    name: 'Tauer Bakery',
    category: 'food',
    food_type: 'colazione',
    latitude: 45.0560,
    longitude: 7.6828,
    address: 'Via Madama Cristina 22, 10125 Torino (TO)',
    sposi_note: 'Deliziosa bakery di ispirazione inglese a San Salvario famosa per i suoi cupcakes finemente decorati, scone e dolci artigianali freschi.',
  },
  // Pizzerie
  {
    id: 'poi-food-da-michele',
    name: 'L\'Antica Pizzeria Da Michele',
    category: 'food',
    food_type: 'pizza',
    latitude: 45.0656,
    longitude: 7.6778,
    address: 'Via S. Quintino 2, 10121 Torino (TO)',
    sposi_note: 'La storica margherita e marinara napoletana a ruota di carretta nel cuore di Torino.',
  },
  {
    id: 'poi-food-capri-blu',
    name: 'Capri Blu Torino',
    category: 'food',
    food_type: 'pizza',
    latitude: 45.0682,
    longitude: 7.6782,
    address: 'Piazza Solferino 8c, 10121 Torino (TO)',
    sposi_note: 'Pizzeria e ristorante partenopeo in Piazza Solferino, celebre per ottime pizze tradizionali e specialità campane.',
  },
  {
    id: 'poi-food-sorbillo',
    name: 'Gino Sorbillo',
    category: 'food',
    food_type: 'pizza',
    latitude: 45.0689,
    longitude: 7.6826,
    address: 'Via XX Settembre 22, 10121 Torino (TO)',
    sposi_note: 'L\'iconica pizza napoletana di Gino Sorbillo a due passi da Via Roma e Piazza San Carlo.',
  },
  {
    id: 'poi-food-wema',
    name: 'WÉMÁ Bogino',
    category: 'food',
    food_type: 'pizza',
    latitude: 45.0681,
    longitude: 7.6866,
    address: 'Via Giambattista Bogino 3, 10123 Torino (TO)',
    sposi_note: 'Pizza contemporanea a lunga lievitazione con cornicione alto e ingredienti gourmet sceltissimi.',
  },
  {
    id: 'poi-food-assaje',
    name: 'Assaje – Pizzeria Gourmet',
    category: 'food',
    food_type: 'pizza',
    latitude: 45.0638,
    longitude: 7.6831,
    address: 'Via Andrea Doria 11, 10123 Torino (TO)',
    sposi_note: 'Pizzeria napoletana d\'eccellenza con impasti tradizionali, integrali e fritti d\'autore.',
  },
  // Pub & Burger
  {
    id: 'poi-food-cheers-superga',
    name: 'Cheers - Bistrot Superga',
    category: 'food',
    food_type: 'pub',
    latitude: 45.0788,
    longitude: 7.7601,
    address: 'Strada Comunale alla Basilica di Superga 45, 10132 Superga (TO)',
    sposi_note: 'Pub panoramico sulla collina di Superga con ottime birre artigianali e vista mozzafiato sulla città.',
  },
  {
    id: 'poi-food-rockburger',
    name: 'Rock Burger® Centro',
    category: 'food',
    food_type: 'pub',
    latitude: 45.0680,
    longitude: 7.6917,
    address: 'Via Roero di Cortanze 2C, 10124 Torino (TO)',
    sposi_note: 'Hamburger gourmet ispirati alle leggende del rock con carne selezionata piemontese e salse fatte in casa.',
  },
  // Piemontese, Piole & Bistrot
  {
    id: 'poi-food-cianci',
    name: 'Piola da Cianci',
    category: 'food',
    food_type: 'cena',
    latitude: 45.0735,
    longitude: 7.6828,
    address: 'Largo IV Marzo 9, 10122 Torino (TO)',
    sposi_note: 'L\'autentica piola torinese in una piazzetta incantevole nel Quadrilatero. Porzioni abbondanti e prezzi super popolari!',
  },
  {
    id: 'poi-food-scannabue',
    name: 'Scannabue',
    category: 'food',
    food_type: 'cena',
    latitude: 45.0565,
    longitude: 7.6822,
    address: 'Largo Saluzzo 25/h, 10125 Torino (TO)',
    sposi_note: 'Bistrot cult di San Salvario con rivisitazioni magistrali della cucina piemontese e carta dei vini eccellente.',
  },
  {
    id: 'poi-food-oca-fola',
    name: 'Trattoria L\'Oca Fola',
    category: 'food',
    food_type: 'cena',
    latitude: 45.0716,
    longitude: 7.6658,
    address: 'Via Bernardino Drovetti 6, 10138 Torino (TO)',
    sposi_note: 'Accogliente trattoria in zona Cit Turin celebre per i piatti d\'oca, pasta fresca fatta in casa e calda ospitalità.',
  },
  {
    id: 'poi-food-madama-piola',
    name: 'Madama Piola',
    category: 'food',
    food_type: 'cena',
    latitude: 45.0578,
    longitude: 7.6835,
    address: 'Via Ormea 6bis, 10125 Torino (TO)',
    sposi_note: 'Osteria contemporanea della tradizione piemontese nel cuore di San Salvario in una cornice curata e accogliente.',
  },
  {
    id: 'poi-food-piola-alfredo',
    name: 'La Piola di Alfredo',
    category: 'food',
    food_type: 'cena',
    latitude: 45.0682,
    longitude: 7.6936,
    address: 'Via Sant\'Ottavio 44, 10124 Torino (TO)',
    sposi_note: 'Ambiente casereccio e verace per assaggiare acciughe al verde, agnolotti al plin e buon vino della casa.',
  },
  {
    id: 'poi-food-la-pista',
    name: 'La Pista Bistrot',
    category: 'food',
    food_type: 'cena',
    latitude: 45.0736,
    longitude: 7.6842,
    address: 'Via Porta Palatina 19, 10122 Torino (TO)',
    sposi_note: 'Raffinato bistrot nel cuore del Quadrilatero Romano vicino alle Porte Palatine, con cucina d\'autore e cocktail ricercati.',
  },
  {
    id: 'poi-food-guarini',
    name: 'Guarini',
    category: 'food',
    food_type: 'cena',
    latitude: 45.0664,
    longitude: 7.6836,
    address: 'Via Guarino Guarini 1B, 10123 Torino (TO)',
    sposi_note: 'Raffinato ristorante tra Via Lagrange e Piazza Carignano, perfetto per aperitivi d\'autore e cene d\'atmosfera.',
  },
  {
    id: 'poi-sightseeing-1',
    name: 'Sacra di San Michele',
    category: 'sightseeing',
    latitude: 45.0978,
    longitude: 7.3444,
    address: 'Via Reale 88, Sant\'Ambrogio di Torino (TO)',
    sposi_note: 'Il monumento simbolo del Piemonte che ha ispirato "Il Nome della Rosa", a soli 15 minuti da Cascina Ranverso.',
  },
  {
    id: 'poi-sightseeing-mole',
    name: 'Mole Antonelliana',
    category: 'sightseeing',
    latitude: 45.0690,
    longitude: 7.6932,
    address: 'Via Montebello 20, 10124 Torino (TO)',
    phone: '+39 011 813 8560',
    website_url: 'https://www.museocinema.it',
    sposi_note: 'Il simbolo inconfondibile di Torino! Sede del Museo del Cinema, con ascensore panoramico sulla città.',
  },
  {
    id: 'poi-sightseeing-egizio',
    name: 'Museo Egizio',
    category: 'sightseeing',
    latitude: 45.0684,
    longitude: 7.6843,
    address: 'Via Accademia delle Scienze 6, 10123 Torino (TO)',
    phone: '+39 011 561 7776',
    website_url: 'https://museoegizio.it',
    sposi_note: 'Il secondo museo egizio più importante al mondo dopo quello del Cairo. Una tappa imperdibile!',
  },
  {
    id: 'poi-sightseeing-piazza-castello',
    name: 'Piazza Castello',
    category: 'sightseeing',
    latitude: 45.0709,
    longitude: 7.6857,
    address: 'Piazza Castello, 10124 Torino (TO)',
    sposi_note: 'Il cuore storico di Torino, circondata dai portici, Palazzo Madama e il Teatro Regio.',
  },
  {
    id: 'poi-sightseeing-palazzo-reale',
    name: 'Palazzo Reale di Torino',
    category: 'sightseeing',
    latitude: 45.0722,
    longitude: 7.6860,
    address: 'Piazzetta Reale 1, 10122 Torino (TO)',
    phone: '+39 011 521 1780',
    website_url: 'https://museireali.beniculturali.it',
    sposi_note: 'L\'antica residenza dei Savoia con i suoi splendidi Giardini Reali e gli appartamenti di rappresentanza.',
  },
  {
    id: 'poi-sightseeing-valentino',
    name: 'Parco del Valentino',
    category: 'sightseeing',
    latitude: 45.0545,
    longitude: 7.6853,
    address: 'Corso Massimo d\'Azeglio, 10126 Torino (TO)',
    sposi_note: 'Il parco cittadino più amato di Torino lungo il Po, ideale per passeggiare e visitare il Borgo Medievale.',
  },
  {
    id: 'poi-sightseeing-superga',
    name: 'Basilica di Superga',
    category: 'sightseeing',
    latitude: 45.0808,
    longitude: 7.7674,
    address: 'Strada Basilica di Superga 73, 10132 Torino (TO)',
    phone: '+39 011 899 7456',
    website_url: 'https://www.basilicadisuperga.com',
    sposi_note: 'Posta sulla collina torinese, offre il panorama più bello sull\'intera città e sull\'arco alpino.',
  },
  {
    id: 'poi-sightseeing-mauto',
    name: 'Museo Nazionale dell\'Automobile',
    category: 'sightseeing',
    latitude: 45.0315,
    longitude: 7.6744,
    address: 'Corso Unità d\'Italia 40, 10126 Torino (TO)',
    phone: '+39 011 677 666',
    website_url: 'https://www.museoauto.com',
    sposi_note: 'Uno dei musei dell\'auto più importanti al mondo che racconta la storia del design e dei motori.',
  },
  {
    id: 'poi-sightseeing-gran-madre',
    name: 'Chiesa Della Gran Madre di Dio',
    category: 'sightseeing',
    latitude: 45.0620,
    longitude: 7.6974,
    address: 'Piazza Gran Madre di Dio 4, 10131 Torino (TO)',
    sposi_note: 'Suggestiva chiesa neoclassica ai piedi della collina, al di là del Po di fronte a Piazza Vittorio.',
  },
  {
    id: 'poi-sightseeing-piazza-carignano',
    name: 'Piazza Carignano',
    category: 'sightseeing',
    latitude: 45.0691,
    longitude: 7.6849,
    address: 'Piazza Carignano, 10123 Torino (TO)',
    sposi_note: 'Una delle piazze barocche più eleganti ed intime di Torino, sede del magnifico Palazzo Carignano.',
  },
  {
    id: 'poi-sightseeing-piazza-vittorio',
    name: 'Piazza Vittorio Veneto',
    category: 'sightseeing',
    latitude: 45.0645,
    longitude: 7.6945,
    address: 'Piazza Vittorio Veneto, 10124 Torino (TO)',
    sposi_note: 'Una delle piazze aperte più grandi d\'Europa, affacciata sul Po di fronte alla Gran Madre. Splendida da vivere la sera sotto i portici!',
  },
  {
    id: 'poi-sightseeing-piazza-san-carlo',
    name: 'Piazza San Carlo',
    category: 'sightseeing',
    latitude: 45.0678,
    longitude: 7.6828,
    address: 'Piazza San Carlo, 10121 Torino (TO)',
    sposi_note: 'Il "Salotto di Torino", famosa per le sue chiese gemelle, la statua del "Cabal \u0027d Brons" e i famosi caffè storici.',
  }
];

export const mockRegistryStages: RegistryStage[] = [
  {
    id: 'stage-1',
    title: 'Pechino & La Grande Muraglia',
    location: 'Pechino & Mutianyu',
    description: 'Dalla maestosa Città Proibita ai passi montani dell\'iconica Grande Muraglia Cinese.',
    target_amount: 2400,
    collected_amount: 0,
    image_url: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'stage-2',
    title: 'L\'Esercito di Terracotta a Xi\'an',
    location: 'Xi\'an & Antica Via della Seta',
    description: 'Alla scoperta dell\'antica capitale imperiale e dei suoi leggendari guerrieri millenari.',
    target_amount: 1200,
    collected_amount: 0,
    image_url: 'https://images.unsplash.com/photo-1598890777032-bde835ba27c2?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'stage-3',
    title: 'Chengdu & i Panda Giganti',
    location: 'Chengdu & Sichuan',
    description: 'Incontro con i dolcissimi panda giganti nella riserva naturale di Chengdu e scoperta dei sapori del Sichuan.',
    target_amount: 1500,
    collected_amount: 0,
    image_url: 'https://images.unsplash.com/photo-1527118732049-c88155f2107c?auto=format&fit=crop&w=1200&q=80',
  },
  {
    id: 'stage-4',
    title: 'Shanghai: Tra Futuro e Tradizione',
    location: 'The Bund & Giardini Yuyuan',
    description: 'Lo scintillante skyline del Bund sul fiume Huangpu, le antiche case da tè e i giardini imperiali.',
    target_amount: 1800,
    collected_amount: 0,
    image_url: 'https://images.unsplash.com/photo-1474181487882-5abf3f0ba6c2?auto=format&fit=crop&w=1200&q=80',
  }
];

export const mockFaqs: FaqItem[] = [
  {
    id: 'faq-dress-code',
    category: 'info',
    question: 'Qual è il dress code consigliato?',
    answer: 'Nessun dress code! Vogliamo solo che stiate comodi e vi godiate la festa. Indossate ciò che vi fa sentire a vostro agio. Dato che saremo in una cascina immersa nel verde, vi suggeriamo solo calzature adatte per camminare agevolmente sui prati.'
  },
  {
    id: 'faq-parking',
    category: 'locations',
    question: 'Come funziona il parcheggio a Cascina Ranverso?',
    answer: 'Cascina Ranverso dispone di un ampio parcheggio privato e gratuito all\'interno della tenuta, comodissimo e a pochi passi dalle zone dedicate alla cerimonia e al ricevimento.'
  },
  {
    id: 'faq-children',
    category: 'info',
    question: 'Posso portare i bambini?',
    answer: 'I bambini sono i benvenuti! Durante il ricevimento a Cascina Ranverso sarà presente un fantastico servizio di animazione in uno spazio a loro dedicato, oltre a un menu bimbi riservato. Così i più piccoli potranno divertirsi e i genitori godersi la festa in totale relax!'
  },
  {
    id: 'faq-gifts',
    category: 'gifts',
    question: 'Cosa desiderate per la lista nozze?',
    answer: 'La vostra presenza è per noi il dono più prezioso! Per chi desiderasse contribuire al nostro sogno, abbiamo aperto la lista nozze per il nostro viaggio di nozze in Cina. Trovate l\'IBAN e tutte le tappe nella sezione Lista Nozze.'
  },
  {
    id: 'faq-food-allergies',
    category: 'info',
    question: 'Come comunico intolleranze o allergie alimentari?',
    answer: 'Puoi indicarci ogni tua esigenza alimentare direttamente compilando il modulo di conferma presenza (RSVP). Il catering preparerà una proposta dedicata per assicurarsi che tutti possano mangiare con gusto e in sicurezza.'
  },
  {
    id: 'faq-party-end',
    category: 'locations',
    question: 'Fino a che ora dureranno i festeggiamenti?',
    answer: 'La location ci permette di ballare fino a tarda notte! Dopo il taglio della torta previsto intorno a mezzanotte, ci sarà il DJ set per scatenarci fino alle 02:00 del mattino.'
  },
  {
    id: 'faq-photos',
    category: 'info',
    question: 'Si potranno scattare foto durante la cerimonia?',
    answer: 'Certamente! Siete liberi di scattare tutte le foto che volete in qualsiasi momento, sia durante la cerimonia che durante il ricevimento. Anzi, ci farà molto piacere se poi le condividerete con noi!'
  },
  {
    id: 'faq-spaces',
    category: 'locations',
    question: 'L\'evento si svolgerà all\'aperto o al chiuso?',
    answer: 'Sfrutteremo tutti i bellissimi spazi della cascina! Tempo permettendo, la cerimonia, l\'aperitivo e il taglio della torta si terranno all\'aperto (altrimenti abbiamo un piano B garantito!), mentre la cena verrà servita al chiuso all\'interno della sala.'
  }
];
